steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/telegram-bot:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/telegram-bot:latest',
      '-f', 'deployment/Dockerfile',
      '.'
    ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/telegram-bot:$BUILD_ID']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/telegram-bot:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '$_SERVICE_NAME',
      '--image', 'gcr.io/$PROJECT_ID/telegram-bot:$BUILD_ID',
      '--region', '$_REGION',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,DEVELOPMENT_MODE=$_DEVELOPMENT_MODE',
      '--service-account', 'telegram-bot-runner@$PROJECT_ID.iam.gserviceaccount.com',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '10',
      '--timeout', '900'
    ]

substitutions:
  _REGION: 'us-central1'  # Change to your preferred region
  _DEVELOPMENT_MODE: 'false'  # Default to true (will be overridden by trigger)
  _SERVICE_NAME: 'telegram-bot'  # Default to test service (will be overridden by trigger)

options:
  logging: CLOUD_LOGGING_ONLY 